In [1]:
from lib.myMLP import *

In [2]:
X_ = np.array([[-1., -2.], [-1, -2]])
W_ = np.array([[2.], [3.]])
b_ = np.array([-3.])
y_ = np.array([1, 2])

In [3]:
X, W, b = Input(), Input(), Input()

In [4]:
z = Linear(X, W, b)

In [5]:
a = Sigmoid(z)

In [6]:
X.value = X_
W.value = W_
b.value = b_

In [7]:
z.forward()

In [8]:
a.forward()

In [9]:
z.value

array([[-11.],
       [-11.]])

In [10]:
a.value

array([[1.67014218e-05],
       [1.67014218e-05]])

In [11]:
Y = Input()
y_hat = np.array([[1.],[1.]])
Y.value = y_hat

In [12]:
e = MSE(Y, a)

In [13]:
e.forward()

In [14]:
e.value

0.4999832987176207

In [15]:
e.backward()
a.backward()
z.backward()

In [19]:
z.gradients[X]

array([[-1.6700864e-05, -2.5051296e-05],
       [-1.6700864e-05, -2.5051296e-05]])

In [4]:
from sklearn.datasets import load_boston
from sklearn.utils import shuffle, resample
import numpy as np
from myMLP.layers import *

# Load data
data = load_boston()
X_ = data['data']
y_ = data['target']

# Normalize data
X_ = (X_ - np.mean(X_, axis=0)) / np.std(X_, axis=0)

n_features = X_.shape[1]
n_hidden = 10
W1_ = np.random.randn(n_features, n_hidden)
b1_ = np.zeros(n_hidden)
W2_ = np.random.randn(n_hidden, 1)
b2_ = np.zeros(1)

# Neural network
X, y = Input(), Input()
W1, b1 = Input(), Input()
W2, b2 = Input(), Input()

l1 = Linear(X, W1, b1)
s1 = Sigmoid(l1)
l2 = Linear(s1, W2, b2)
cost = MSE(y, l2)

feed_dict = {
    X: X_,
    y: y_,
    W1: W1_,
    b1: b1_,
    W2: W2_,
    b2: b2_
}

epochs = 1000
# Total number of examples
m = X_.shape[0]
batch_size = 11
steps_per_epoch = m // batch_size

graph = topological_sort(feed_dict)
print(graph)
print(X)
print(l1)
trainables = [W1, b1, W2, b2]

print("Total number of examples = {}".format(m))

cost = []
# Step 4
for i in range(epochs):
    loss = 0
    for j in range(steps_per_epoch):
        X_batch, y_batch = resample(X_, y_, n_samples=batch_size)

        # Reset value of X and y Inputs
        X.value = X_batch
        y.value = y_batch

        # Step 2
        forward_and_backward(graph)

        # Step 3
        sgd_update(trainables)

        loss += graph[-1].value
    if (i%100 == 0):
        print("Epoch: {}, Loss: {:.3f}".format(i+1, loss/steps_per_epoch))
    cost.append(loss)

[<myMLP.layers.Input object at 0x000001E3D6078B00>, <myMLP.layers.Input object at 0x000001E398B2F5C0>, <myMLP.layers.Input object at 0x000001E3D606EFD0>, <myMLP.layers.Input object at 0x000001E398B2FCC0>, <myMLP.layers.Input object at 0x000001E398B2FCF8>, <myMLP.layers.Input object at 0x000001E398B2FD68>]
[<myMLP.layers.Input object at 0x000001E3D6078B00>, <myMLP.layers.Input object at 0x000001E398B2F5C0>, <myMLP.layers.Input object at 0x000001E3D606EFD0>, <myMLP.layers.Input object at 0x000001E398B2FCC0>, <myMLP.layers.Input object at 0x000001E398B2FCF8>, <myMLP.layers.Input object at 0x000001E398B2FD68>]
[<myMLP.layers.Input object at 0x000001E398B2FCC0>, <myMLP.layers.Input object at 0x000001E398B2FCF8>, <myMLP.layers.Input object at 0x000001E3D6078B00>, <myMLP.layers.Input object at 0x000001E398B2FD68>, <myMLP.layers.Input object at 0x000001E398B2F5C0>, <myMLP.layers.Input object at 0x000001E3D606EFD0>, <myMLP.layers.Linear object at 0x000001E398B2FD30>, <myMLP.layers.Sigmoid objec

NameError: name 'sgd_update' is not defined

In [6]:
import numpy as np
X_ = np.array([[-1., -2.], [-1, -2]])
y = layers.Input()
f = models.Linear()
z = f(X_)
a = layers.Sigmoid(z)
cost = layers.MSE(y, a)

# W_ = np.array([[2.], [3.]])
# b_ = np.array([-3.])
y_ = np.array([1, 2])

feed_dict = {
    z.in_nodes[0]: X_,
    y: y_,
    z.in_nodes[1]: f.W.value,
    z.in_nodes[2]: f.b.value,
}

graph = layers.topological_sort(feed_dict)
forward_and_backward(graph)
# return the gradients for each Input
gradients = [t.gradients[t] for t in [X, y, W, b]]

"""
Expected output

[array([[ -3.34017280e-05,  -5.01025919e-05],
       [ -6.68040138e-05,  -1.00206021e-04]]), array([[ 0.9999833],
       [ 1.9999833]]), array([[  5.01028709e-05],
       [  1.00205742e-04]]), array([ -5.01028709e-05])]
"""
print(gradients)

NameError: name 'topological_sort' is not defined

In [1]:
from myMLP import models, layers

In [33]:
from sklearn.datasets import load_boston
from sklearn.utils import shuffle, resample

# Load data
data = load_boston()
X_ = data['data']
y_ = data['target']

# Normalize data
X_ = (X_ - np.mean(X_, axis=0)) / np.std(X_, axis=0)

n_features = X_.shape[1]
n_hidden = 10
W1_ = np.random.randn(n_features, n_hidden)
b1_ = np.zeros(n_hidden)

# Neural network
X, y = Input(), Input()
W1, b1 = Input(), Input()

l1 = layers.Linear(X, W1, b1)
s1 = layers.Sigmoid(l1)

In [29]:
X = layers.Input()

In [19]:
print(X.value)

10


In [18]:
X.value = 10

In [21]:
y = models.Sigmoid()

In [23]:
z = y(X)

In [24]:
z.forward()

In [25]:
z.value

0.9999546021312976