In [1]:
from lib.myMLP import *

In [2]:
X_ = np.array([[-1., -2.], [-1, -2]])
W_ = np.array([[2.], [3.]])
b_ = np.array([-3.])
y_ = np.array([1, 2])

In [3]:
X, W, b = Input(), Input(), Input()

In [4]:
z = Linear(X, W, b)

In [5]:
a = Sigmoid(z)

In [6]:
X.value = X_
W.value = W_
b.value = b_

In [7]:
z.forward()

In [8]:
a.forward()

In [9]:
z.value

array([[-11.],
       [-11.]])

In [10]:
a.value

array([[1.67014218e-05],
       [1.67014218e-05]])

In [11]:
Y = Input()
y_hat = np.array([[1.],[1.]])
Y.value = y_hat

In [12]:
e = MSE(Y, a)

In [13]:
e.forward()

In [14]:
e.value

0.4999832987176207

In [15]:
e.backward()
a.backward()
z.backward()

In [19]:
z.gradients[X]

array([[-1.6700864e-05, -2.5051296e-05],
       [-1.6700864e-05, -2.5051296e-05]])

In [ ]:
from myMLP import *

In [28]:
X, W, b = Input(), Input(), Input()

In [27]:
from myMLP import *
